---
kind: pipeline
type: docker
name: build

steps:
  - name: publish
    image: plugins/docker
    settings:
      mirror:
        from_secret: DOCKER_MIRROR
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: aricodes/kobo-toolchain
      tags:
        - latest
